name: Update Activity Timeline

on:
  schedule:
    - cron: "0 17 * * *" # Customize CRON run timing - like this it runs hourly
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch & Render Activity
        uses: FreddyMSchubert/github-activity-timeline@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: "Jordancuadro" # Insert your username here
          max_items: "5"
          event_templates: > # Customize what to display here
            {
              "pr_opened": "{{index}}. ğŸ†• PR [{{repo}}#{{payload.pull_request.number}}]({{payload.pull_request.html_url}}) opened: â€œ{{payload.pull_request.title.slice(0,50)}}â€¦â€",
              "pr_closed": "{{index}}. {{payload.pull_request.merged ? 'ğŸ¯ Merged' : 'âŒ Closed'}} PR [{{repo}}#{{payload.pull_request.number}}]({{payload.pull_request.html_url}}) by {{actor}}",
              "pr_merged": "...",
              "push": "..."
            }

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md && git diff --cached --quiet || git commit -m "chore: update activity"
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
